# Spring Application
spring.application.name=sms
  
  # Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sms
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
  
  # JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
  
  # JoinFaces Configuration
spring.joinfaces.faces.project-stage=Development
spring.joinfaces.primefaces.theme=omega
  
  # MyBatis Configuration
mybatis.mapper-locations=classpath*:mapper/*.xml
mybatis.type-aliases-package=mm.com.dat.sms
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl