ipoTaxPercentage=0.3
ipoCommissionPercentage=0.3
transferTaxPercentage=1
ipoServiceCharge=0.3
transferServiceCharge=12000
commissionPercentage=0.3
clientPhotosPath=C:/simbaplatform/jboss-as-7.1.1.Final/standalone/clientphotos
importFilePath=C:/simbaplatform/jboss-as-7.1.1.Final/standalone/import
formEtempFilePath=/tmp/SrchFormE/
backDateTransferPrice = 10000.00