#User Role Entry
ug.userRoleOne = Check tick on "Check All" if you want to select all items.
ug.userRoleTwo = Check tick on the square box each if you want to select the item.

#Product Input
ug.productRegOne = Estimated price.
ug.productRegTwo = Minimum share movement.

#Product Issue
ug.productIssOne = Total issued quantity.

#Common
ug.commonOne = Put ID or Name or NRC.
ug.commonTwo = Put quantity or use arrows.
ug.commonThree = Click on calendar picture. 
ug.commonFour = Put Name or NRC.
ug.commonFive = Put product name first.
ug.commonSix = Put ID or Name.

#Behalf Of ShareHolder Input
ug.dividendPaymentOne = On Behalf Of ShareHolder.
ug.dividendPaymentTwo = NRC Number.
ug.dividendPaymentThree = Bank Account No.